defaults:
  - _base_

deter: 512
hidden: 1024
discrete: 64
depth: 64
units: 1024
act: 'SiLU'
norm: True

transformer:
  #feat_deter_dim: 1024
  #feat_stoch_dim: 512
  feat_deter_dim: null
  feat_stoch_dim: null
